- hosts: targets

  tasks:
    - name: Print WhoAmI
      shell: whoami

  roles:
    - role: java
      when: "ansible_os_family == 'Debian'"
      java_package:
        - openjdk-8-jdk
      become: yes

    - role: puppet
      become: yes
