---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Puppet for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - system
    - configuration
    - cm
    - orchestration
    - server
    - puppet
